theme: jekyll-theme-minimal
logo: https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DEXrjhDfQp6E&psig=AOvVaw1rAhXQF3Bx4-0evuBH40SI&ust=1733510468049000&source=images&cd=vfe&opi=89978449&ved=0CBAQjRxqFwoTCKiH_e-jkYoDFQAAAAAdAAAAABAE
title: Spogebob
