theme: jekyll-theme-minimal
logo: https://www.google.com/url?sa=i&url=https%3A%2F%2Fallkidsbike.org%2Fambassador%2Ftroy-lee%2F&psig=AOvVaw1fiMpUP8kfL4TKCPpxG2Zv&ust=1733510686829000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCPin49ekkYoDFQAAAAAdAAAAABAJ
title: Spogebob
